name:
  *: hksagentur.webform.blueprint.name
icon: email
tabs:
  content:
    label:
      *: hksagentur.webform.blueprint.content.label
    icon: document
    fields:
      title:
        type: text
        label:
          *: hksagentur.webform.blueprint.title.label
        icon: headline
      text:
        type: writer
        label:
          *: hksagentur.webform.blueprint.text.label
      form:
        type: select
        label:
          *: hksagentur.webform.blueprint.form.label
        required: true
        options:
          type: query
          query: kirby.collection('webforms')
          value: "{{ item.getPath }}"
          text: "{{ item.getLabel }}"
  settings:
    label:
      *: hksagentur.webform.blueprint.settings.label
    icon: cog
    fields:
      action:
        type: toggles
        label:
          *: hksagentur.webform.blueprint.action.label
        default: email
        options:
          - value: email
            icon: email
            text:
              *: hksagentur.webform.blueprint.action.email
          - value: database
            icon: server
            text:
              *: hksagentur.webform.blueprint.action.database
          - value: webhook
            icon: url
            text:
              *: hksagentur.webform.blueprint.action.webhook
      emailSubject:
        type: text
        label:
          *: hksagentur.webform.blueprint.emailSubject.label
        icon: headline
        required: false
        when:
          action: email
      emailFrom:
        type: text
        label:
          *: hksagentur.webform.blueprint.emailFrom.label
        icon: email
        required: false
        counter: false
        when:
          action: email
      emailTo:
        type: text
        label:
          *: hksagentur.webform.blueprint.emailTo.label
        icon: email
        required: false
        counter: false
        when:
          action: email
      emailReplyTo:
        type: text
        label:
          *: hksagentur.webform.blueprint.emailReplyTo.label
        icon: email
        required: false
        counter: false
        when:
          action: email
      databaseTable:
        type: text
        label:
          *: hksagentur.webform.blueprint.databaseTable.label
        default: submissions
        required: true
        counter: false
        when:
          action: database
      webhookUrl:
        type: text
        label:
          *: hksagentur.webform.blueprint.webhookUrl.label
        icon: url
        required: true
        counter: false
        when:
          action: webhook
      lineMessages:
        type: line
      successMessage:
        type: writer
        label:
          *: hksagentur.webform.blueprint.successMessage.label
        help:
          *: hksagentur.webform.blueprint.successMessage.help
        icon: check
      errorMessage:
        type: writer
        label:
          *: hksagentur.webform.blueprint.errorMessage.label
        help:
          *: hksagentur.webform.blueprint.errorMessage.help
        icon: cross
