<?php

return [
    'blocks/webform' => dirname(__DIR__) . '/snippets/blocks/webform.php',
    'webform/button-group' => dirname(__DIR__) . '/snippets/components/button-group.php',
    'webform/button' => dirname(__DIR__) . '/snippets/components/button.php',
    'webform/checkbox-group' => dirname(__DIR__) . '/snippets/components/checkbox-group.php',
    'webform/checkbox' => dirname(__DIR__) . '/snippets/components/checkbox.php',
    'webform/cluster' => dirname(__DIR__) . '/snippets/components/cluster.php',
    'webform/datalist' => dirname(__DIR__) . '/snippets/components/datalist.php',
    'webform/datetime' => dirname(__DIR__) . '/snippets/components/datetime.php',
    'webform/file' => dirname(__DIR__) . '/snippets/components/file.php',
    'webform/field' => dirname(__DIR__) . '/snippets/components/field.php',
    'webform/fieldset' => dirname(__DIR__) . '/snippets/components/fieldset.php',
    'webform/form' => dirname(__DIR__) . '/snippets/components/form.php',
    'webform/grid' => dirname(__DIR__) . '/snippets/components/grid.php',
    'webform/help' => dirname(__DIR__) . '/snippets/components/help.php',
    'webform/hidden' => dirname(__DIR__) . '/snippets/components/hidden.php',
    'webform/honeypot' => dirname(__DIR__) . '/snippets/components/honeypot.php',
    'webform/inline-error' => dirname(__DIR__) . '/snippets/components/inline-error.php',
    'webform/label' => dirname(__DIR__) . '/snippets/components/label.php',
    'webform/message' => dirname(__DIR__) . '/snippets/components/message.php',
    'webform/radio-group' => dirname(__DIR__) . '/snippets/components/radio-group.php',
    'webform/radio' => dirname(__DIR__) . '/snippets/components/radio.php',
    'webform/select' => dirname(__DIR__) . '/snippets/components/select.php',
    'webform/stack' => dirname(__DIR__) . '/snippets/components/stack.php',
    'webform/time-trap' => dirname(__DIR__) . '/snippets/components/time-trap.php',
    'webform/text-input' => dirname(__DIR__) . '/snippets/components/text-input.php',
    'webform/textarea' => dirname(__DIR__) . '/snippets/components/textarea.php',
];
